# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"A\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x11\n\x0fGetUsersRequest\".\n\x10GetUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x13GetUserByIdResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x12\x43reateUsersRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"0\n\x13\x43reateUsersResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x12UpdateUsersRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"0\n\x13UpdateUsersResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\" \n\x12\x44\x65leteUsersRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x13\x44\x65leteUsersResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User2\xe6\x02\n\x05Users\x12=\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\"\x00\x12\x46\n\x0bGetUserById\x12\x19.users.GetUserByIdRequest\x1a\x1a.users.GetUserByIdResponse\"\x00\x12\x46\n\x0b\x43reateUsers\x12\x19.users.CreateUsersRequest\x1a\x1a.users.CreateUsersResponse\"\x00\x12\x46\n\x0bUpdateUsers\x12\x19.users.UpdateUsersRequest\x1a\x1a.users.UpdateUsersResponse\"\x00\x12\x46\n\x0b\x44\x65leteUsers\x12\x19.users.DeleteUsersRequest\x1a\x1a.users.DeleteUsersResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=22
  _USER._serialized_end=87
  _GETUSERSREQUEST._serialized_start=89
  _GETUSERSREQUEST._serialized_end=106
  _GETUSERSRESPONSE._serialized_start=108
  _GETUSERSRESPONSE._serialized_end=154
  _GETUSERBYIDREQUEST._serialized_start=156
  _GETUSERBYIDREQUEST._serialized_end=188
  _GETUSERBYIDRESPONSE._serialized_start=190
  _GETUSERBYIDRESPONSE._serialized_end=238
  _CREATEUSERSREQUEST._serialized_start=240
  _CREATEUSERSREQUEST._serialized_end=287
  _CREATEUSERSRESPONSE._serialized_start=289
  _CREATEUSERSRESPONSE._serialized_end=337
  _UPDATEUSERSREQUEST._serialized_start=339
  _UPDATEUSERSREQUEST._serialized_end=386
  _UPDATEUSERSRESPONSE._serialized_start=388
  _UPDATEUSERSRESPONSE._serialized_end=436
  _DELETEUSERSREQUEST._serialized_start=438
  _DELETEUSERSREQUEST._serialized_end=470
  _DELETEUSERSRESPONSE._serialized_start=472
  _DELETEUSERSRESPONSE._serialized_end=520
  _USERS._serialized_start=523
  _USERS._serialized_end=881
# @@protoc_insertion_point(module_scope)
